import JSZip from 'jszip';
import type { Schema, Tokens } from '../types/schema';

export type ExportPackage = {
  metadata:{generator:string; version:string; format:string; generatedAtLocal:string};
  schema:{product:string; pattern:string; strategy:string; headline:string; subhead:string; requirements:Schema['requirements']; directives:string[]};
  designTokens:Tokens;
  component:{filename:string; language:string; code:string};
  readme:string;
};

export const EXPORT_GENERATOR = 'InterfaceForge';
export const EXPORT_VERSION = '1.0.0';
const DETERMINISTIC_GENERATED_AT = 'deterministic-local-generation';

export function buildExportPackage(schema:Schema,design:Tokens):ExportPackage{const metadata={generator:EXPORT_GENERATOR,version:EXPORT_VERSION,format:'interfaceforge-export-package-v1',generatedAtLocal:DETERMINISTIC_GENERATED_AT}; const schemaSummary={product:schema.product,pattern:schema.pattern,strategy:schema.strategy,headline:schema.headline,subhead:schema.subhead,requirements:schema.requirements,directives:schema.directives}; const componentCode=`/* Generated by ${EXPORT_GENERATOR} v${EXPORT_VERSION} */\n/* Local deterministic generation package */\n\nexport const exportMetadata = ${JSON.stringify(metadata,null,2)};\nexport const exportSchema = ${JSON.stringify(schemaSummary,null,2)};\nexport const exportDesignTokens = ${JSON.stringify(design,null,2)};`; const readme=`# InterfaceForge Local Export\n\nGenerated by ${EXPORT_GENERATOR} v${EXPORT_VERSION}.\n\nThis package is generated locally and deterministically from your prompt + token state in-browser (no backend).\n\n## Included files\n- schema.json (schema, requirements, directives, metadata)\n- design-tokens.json\n- GeneratedComponent.ts (generated component code + metadata)\n- README.md\n`; return {metadata,schema:schemaSummary,designTokens:design,component:{filename:'GeneratedComponent.ts',language:'typescript',code:componentCode},readme};}
export function exportPackageText(pkg:ExportPackage){return `/* Generated by ${pkg.metadata.generator} v${pkg.metadata.version} */\n/* ${pkg.metadata.format} */\n\nexport const exportPackage = ${JSON.stringify(pkg,null,2)};`;}
export async function downloadZip(name:string,pkg:ExportPackage){const zip = new JSZip(); zip.file('schema.json',JSON.stringify({metadata:pkg.metadata,schema:pkg.schema,requirements:pkg.schema.requirements,directives:pkg.schema.directives},null,2)); zip.file('design-tokens.json',JSON.stringify(pkg.designTokens,null,2)); zip.file(pkg.component.filename,pkg.component.code); zip.file('README.md',pkg.readme); const blob = await zip.generateAsync({type:'blob'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); URL.revokeObjectURL(a.href);}
