import type { Schema, Tokens } from '../types/schema';

export function exportCode(schema:Schema,design:Tokens){return`/* Generated by InterfaceForge */\nexport const schema = ${JSON.stringify(schema,null,2)};\nexport const designTokens = ${JSON.stringify(design,null,2)};`}

export function download(name:string,content:string){const blob=new Blob([content],{type:'text/plain'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); URL.revokeObjectURL(a.href)}
