import type { Pattern } from '../types/schema';

export type PromptFixture = {
  id: string;
  prompt: string;
  expectedPattern: Pattern;
  expectedStrategy?: string;
  expectedLayoutIntent?: string;
  expectedBlocks: string[];
  expectedValues: string[];
  expectedDirectives: string[];
  expectedInteractions: string[];
  minQualityScore: number;
  notes: string;
};

export const promptFixtures: PromptFixture[] = [
  { id: 'pricing-growth-compare', prompt: 'Build a pricing page for NimbusDesk with Starter $19/month, Team $49/month, and Scale $129/month. Include monthly annual billing toggle, comparison matrix, enterprise contact sales, and highlight the premium plan with subtle glow.', expectedPattern: 'pricing', expectedStrategy: 'grid', expectedBlocks: ['pricingCards', 'billingToggle', 'comparisonMatrix', 'enterpriseContact', 'ctaBand'], expectedValues: ['$19/month', '$49/month', '$129/month'], expectedDirectives: ['glow'], expectedInteractions: ['select_plan'], minQualityScore: 80, notes: 'Canonical SaaS pricing benchmark.' },
  { id: 'pricing-agency', prompt: 'Create modern pricing tiers for PixelForge: Basic $29/month, Pro $79/month, Elite $149/month. Add yearly option and make the final card larger by 15% with medium bevel.', expectedPattern: 'pricing', expectedBlocks: ['pricingCards', 'billingToggle', 'ctaBand'], expectedValues: ['$29/month', '$79/month', '$149/month'], expectedDirectives: ['bevel'], expectedInteractions: ['select_plan'], minQualityScore: 78, notes: 'Tests directive execution on final card.' },
  { id: 'dashboard-ops-center', prompt: 'Create a dashboard for logistics ops with revenue, active shipments, SLA health, and incident feed. Keep it local-first and export-ready.', expectedPattern: 'dashboard', expectedLayoutIntent: 'stacked', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: [], minQualityScore: 70, notes: 'Pattern detection for dashboard.' },
  { id: 'settings-security', prompt: 'Build account settings for admin teams with SSO toggle, session timeout control, audit log export, and private mode switch.', expectedPattern: 'settings', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['toggle_setting'], minQualityScore: 72, notes: 'Settings interactions and controls extraction.' },
  { id: 'checkout-dtc', prompt: 'Design a checkout flow with cart summary, tax line, total, promo code input, and purchase CTA for local exports only.', expectedPattern: 'checkout', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['checkout'], minQualityScore: 70, notes: 'Checkout intent and action behavior.' },
  { id: 'chat-support-inbox', prompt: 'Create a support inbox chat workspace with unread queue, agent handoff notes, canned replies, and send message action.', expectedPattern: 'chat', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['send_chat'], minQualityScore: 70, notes: 'Chat pattern and interaction behavior.' },
  { id: 'calendar-booking-coach', prompt: 'Build a booking calendar for coaching sessions with available time slots, timezone label, and confirm booking CTA.', expectedPattern: 'calendar', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['select_slot'], minQualityScore: 72, notes: 'Calendar pattern and selectable slots.' },
  { id: 'onboarding-wizard', prompt: 'Create a custom onboarding flow called AtlasStart with step 1 identity setup, step 2 workspace preferences, step 3 import data, plus invite teammates CTA.', expectedPattern: 'custom', expectedBlocks: ['onboardingSteps', 'ctaBand'], expectedValues: ['identity setup', 'workspace preferences', 'import data', 'invite teammates'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 76, notes: 'Onboarding custom flow should create onboardingSteps.' },
  { id: 'mobile-cards-retail', prompt: 'Design a custom mobile cards interface for flash deals with swipe cards, stock badge, discount percent, and buy now action.', expectedPattern: 'custom', expectedBlocks: ['customRequirementGrid', 'ctaBand'], expectedValues: ['swipe cards', 'stock badge', 'discount'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 74, notes: 'Mobile card language with custom fallback.' },
  { id: 'command-console-devops', prompt: 'Create custom command console control center with deploy status metrics, pipeline controls, rollback action, and activity stream.', expectedPattern: 'custom', expectedBlocks: ['metricGrid', 'settingsControls', 'activityFeed', 'ctaBand'], expectedValues: ['deploy status', 'pipeline controls', 'rollback', 'activity'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 76, notes: 'Console keywords should trigger control-center block set.' },
  { id: 'analytics-panel-growth', prompt: 'Build custom analytics panel with funnel conversion, CAC, retention curve, and date-range controls for weekly monthly view.', expectedPattern: 'custom', expectedBlocks: ['metricGrid', 'settingsControls', 'activityFeed', 'ctaBand'], expectedValues: ['funnel conversion', 'cac', 'retention', 'date-range'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 74, notes: 'Analytics vocabulary in custom mode.' },
  { id: 'enterprise-security-ui', prompt: 'Create a custom enterprise security center with risk score metric, policy controls, compliance evidence list, and incident escalation CTA.', expectedPattern: 'custom', expectedBlocks: ['metricGrid', 'settingsControls', 'activityFeed', 'ctaBand'], expectedValues: ['risk score', 'policy controls', 'compliance', 'incident escalation'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 76, notes: 'Enterprise controls-heavy custom strategy.' },
  { id: 'custom-component-token-editor', prompt: 'Create a custom component prompt for token editor with theme palette rows, semantic color preview, and save token set action.', expectedPattern: 'custom', expectedBlocks: ['customRequirementGrid', 'ctaBand'], expectedValues: ['theme palette', 'semantic color'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 74, notes: 'Custom component prompt variant.' },
  { id: 'pricing-startup-annual', prompt: 'Pricing screen for DevRelay with Launch $12/month, Build $39/month, Scale $99/month and annual billing copy plus contact sales for enterprise.', expectedPattern: 'pricing', expectedBlocks: ['pricingCards', 'billingToggle', 'enterpriseContact', 'ctaBand'], expectedValues: ['$12/month', '$39/month', '$99/month'], expectedDirectives: [], expectedInteractions: ['select_plan'], minQualityScore: 78, notes: 'Pricing with enterprise pathway.' },
  { id: 'dashboard-finance', prompt: 'Design finance dashboard showing ARR, churn, expansion revenue, top accounts table, and executive summary card.', expectedPattern: 'dashboard', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: [], minQualityScore: 70, notes: 'Finance metrics dashboard.' },
  { id: 'settings-notifications', prompt: 'Build user settings with email digest toggle, sms alerts switch, locale selector, and export privacy controls.', expectedPattern: 'settings', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['toggle_setting'], minQualityScore: 72, notes: 'Notification settings prompt.' },
  { id: 'checkout-b2b-procurement', prompt: 'Create checkout for procurement with PO number field, tax exempt checkbox, seat quantity, and complete purchase button.', expectedPattern: 'checkout', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['checkout'], minQualityScore: 70, notes: 'B2B checkout language.' },
  { id: 'chat-customer-success', prompt: 'Build client success chat inbox with SLA breach tags, conversation filters, assignment controls, and send update CTA.', expectedPattern: 'chat', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['send_chat'], minQualityScore: 70, notes: 'Support inbox operations.' },
  { id: 'calendar-clinic', prompt: 'Create clinic booking calendar with provider selector, available slots, cancellation notice, and reserve appointment action.', expectedPattern: 'calendar', expectedBlocks: ['hero'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['select_slot'], minQualityScore: 72, notes: 'Healthcare booking prompt.' },
  { id: 'onboarding-data-migration', prompt: 'Design custom onboarding with import CSV step, map fields step, validation summary, and launch workspace CTA.', expectedPattern: 'custom', expectedBlocks: ['onboardingSteps', 'ctaBand'], expectedValues: ['import csv', 'map fields', 'validation summary', 'launch workspace'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 76, notes: 'Data migration onboarding.' },
  { id: 'mobile-cards-wallet', prompt: 'Create custom mobile wallet cards with balance, recent transactions chip, freeze card toggle, and quick transfer action.', expectedPattern: 'custom', expectedBlocks: ['customRequirementGrid', 'ctaBand'], expectedValues: ['balance', 'freeze card', 'quick transfer'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 74, notes: 'Fintech mobile cards.' },
  { id: 'command-console-incident', prompt: 'Build custom incident command console with severity metric, owner controls, timeline feed, and resolve incident CTA.', expectedPattern: 'custom', expectedBlocks: ['metricGrid', 'settingsControls', 'activityFeed', 'ctaBand'], expectedValues: ['severity', 'owner controls', 'timeline', 'resolve incident'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 76, notes: 'Incident management console.' },
  { id: 'analytics-panel-product', prompt: 'Create custom product analytics panel with feature adoption, DAU trend, cohort retention, and segment filter controls.', expectedPattern: 'custom', expectedBlocks: ['metricGrid', 'settingsControls', 'activityFeed', 'ctaBand'], expectedValues: ['feature adoption', 'dau trend', 'cohort retention', 'segment filter'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 74, notes: 'Product analytics panel.' },
  { id: 'enterprise-security-audit', prompt: 'Custom enterprise security UI with audit trail timeline, permission controls, policy exceptions queue, and approve remediation CTA.', expectedPattern: 'custom', expectedBlocks: ['metricGrid', 'settingsControls', 'activityFeed', 'ctaBand'], expectedValues: ['audit trail', 'permission controls', 'policy exceptions', 'remediation'], expectedDirectives: [], expectedInteractions: ['custom'], minQualityScore: 76, notes: 'Audit-first enterprise security prompt.' },
  { id: 'custom-component-builder', prompt: 'Create custom component builder interface with variant matrix, slot editor, prop controls, and export package action. Add subtle highlight on header.', expectedPattern: 'custom', expectedBlocks: ['metricGrid', 'settingsControls', 'activityFeed', 'proofStrip', 'ctaBand'], expectedValues: ['variant matrix', 'slot editor', 'prop controls', 'export package'], expectedDirectives: ['highlight'], expectedInteractions: ['custom'], minQualityScore: 75, notes: 'Custom component builder with directive.' },
  { id: 'visualization-usa-bases-globe', prompt: 'an interactive slow spinning globe with glowing markers over every USA military base that exists', expectedPattern: 'visualization', expectedBlocks: ['globeVisualization', 'geoMarkerLayer', 'markerLegend', 'animationControls', 'datasetNotice'], expectedValues: [], expectedDirectives: [], expectedInteractions: ['Pause rotation'], minQualityScore: 80, notes: 'Regression fixture for visualization renderer and dataset notice.' }
];

