export type Pattern = 'pricing'|'dashboard'|'settings'|'checkout'|'chat'|'calendar'|'custom';
export type Plan = { name:string; price:string; annual:string; description:string; features:string[]; visual:{featured:boolean;scale:number;glow:string;bevel:string;badge?:string} };
export type Schema = { pattern:Pattern; strategy:string; product:string; headline:string; subhead:string; action:string; features:string[]; plans:Plan[]; metrics:{label:string;value:string;delta:string}[]; toggles:string[]; messages:string[]; slots:string[]; lineItems:{label:string;value:string}[]; requirements:{label:string;source:string}[]; directives:string[] };
type Span={start:number;end:number;text:string;reason:string}; type Dir={target:string;effect:'scale'|'glow'|'bevel'|'highlight';magnitude:string;span:Span};
const K:Record<Pattern,string[]>={pricing:['pricing','price','plans','tiers','subscription','billing'],dashboard:['dashboard','cockpit','analytics','metrics','kpi','revenue'],settings:['settings','preferences','toggles','security'],checkout:['checkout','cart','payment','purchase'],chat:['chat','messages','inbox','support'],calendar:['calendar','booking','schedule','slots'],custom:['custom']};
const w=(s:string)=>s.toLowerCase().replace(/[.,;:!?()]/g,' ').split(/\s+/).filter(Boolean); const norm=(s:string)=>w(s).join(' '); const title=(s:string)=>s.split(' ').filter(Boolean).map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' ');
const has=(t:string,l:string[])=>l.some(x=>t.includes(x));
function items(p:string){const l=p.toLowerCase();const a=[' with ',' including ',' plus ',' columns ',' fields ',' toggles '].find(x=>l.includes(x));const r=a?p.slice(l.indexOf(a)+a.length):p;return r.replace(/ and /gi,',').replace(/ plus /gi,',').split(',').map(x=>x.trim().replace(/[.]/g,'')).filter(x=>x.length>2).slice(0,10)}
function detect(p:string){const t=norm(p); return (Object.keys(K) as Pattern[]).map(pattern=>({pattern,score:K[pattern].reduce((s,k)=>s+(t.includes(k)?2:0),0)})).sort((a,b)=>b.score-a.score)}
const spans=(p:string,re:RegExp,reason:string)=>Array.from(p.matchAll(re)).map(m=>({start:m.index??0,end:(m.index??0)+m[0].length,text:m[0],reason}));
function entities(p:string){return{prices:spans(p,/\$\s?\d[\d,]*(?:\.\d+)?(?:\s?\/\s?(?:month|mo|year|yr|week|day))?/gi,'price'),ctas:spans(p,/\b(?:launch|save|send|purchase|book|continue)\b[^,.]*/gi,'cta'),fields:items(p).map(x=>({start:Math.max(0,p.toLowerCase().indexOf(x.toLowerCase())),end:Math.max(0,p.toLowerCase().indexOf(x.toLowerCase()))+x.length,text:x,reason:'field'})),product:(()=>{const m=p.match(/(?:called|named)\s+([^.,]+)/i);return m?{start:m.index??0,end:(m.index??0)+m[1].length,text:m[1],reason:'product'}:null})()}}
function directives(p:string){const out:Dir[]=[]; const tars=Array.from(p.matchAll(/(final\s+\w+\s+card|premium\s+plan|this\s+card|\$\s?\d[\d,]*(?:\/\w+)?\s+pricing\s+card)/gi));
 for(const t of tars){const txt=t[0].toLowerCase();const s={start:t.index??0,end:(t.index??0)+t[0].length,text:t[0],reason:'directive'}; if(/stand out|highlight/.test(p.toLowerCase())) out.push({target:txt,effect:'highlight',magnitude:'high',span:s}); if(/bigger|increase size|scale|larger/.test(p.toLowerCase())) out.push({target:txt,effect:'scale',magnitude:(p.match(/(\d+)%/)?.[1]??'20'),span:s}); if(/glow/.test(p.toLowerCase())) out.push({target:txt,effect:'glow',magnitude:'medium',span:s}); if(/bevel|3d/.test(p.toLowerCase())) out.push({target:txt,effect:'bevel',magnitude:'medium',span:s}); }
 const uniq=new Map<string,Dir>(); out.forEach(d=>uniq.set(`${d.target}:${d.effect}`,d)); const all=[...uniq.values()]; const maxScale=all.filter(d=>d.effect==='scale').sort((a,b)=>Number(b.magnitude)-Number(a.magnitude))[0]; return maxScale?[...all.filter(d=>d.effect!=='scale'),maxScale]:all; }
function makePlans(prompt:string, feats:string[], ds:Dir[], prices:string[]):Plan[]{const n=Math.max(prices.length,3);const names=['Starter','Growth','Pro','Premium','Scale'];const featured=ds[0]?.target??'premium plan';const scale=Number(ds.find(d=>d.effect==='scale')?.magnitude??0);return Array.from({length:n}).map((_,i)=>({name:names[i]||`Plan ${i+1}`,price:prices[i]||`$${(i+1)*49}/month`,annual:(prices[i]||`$${(i+1)*49}/month`).replace('/month','/year'),description:i===n-1?'The most complete package for high-volume teams.':'More polish, power, and export control.',features:[feats[i%feats.length]||'Production JSX','Responsive card layout','Production-ready source'],visual:{featured:i===n-1||featured.includes((prices[i]||'').toLowerCase()),scale:i===n-1?1+(scale/100):1,glow:ds.some(d=>d.effect==='glow')?'medium':'none',bevel:ds.some(d=>d.effect==='bevel')?'medium':'none',badge:'Best value'}}))}
export function buildSchema(prompt:string):Schema{const d=detect(prompt);const pat=(d[0]?.score??0)>0?d[0].pattern:'custom';const e=entities(prompt);const ds=directives(prompt);const prod=e.product?title(e.product.text.split(' with ')[0]):'InterfaceForge';const feats=[...new Set(e.fields.map(f=>title(f.text)).filter(x=>!x.startsWith('$')).slice(0,4))];const cta=norm(prompt).includes('launch')?'Launch now':norm(prompt).includes('save')?'Save changes':norm(prompt).includes('send')?'Send reply':norm(prompt).includes('purchase')?'Complete purchase':norm(prompt).includes('book')?'Book session':pat==='pricing'?'Choose plan':'Continue';const pr=e.prices.map(x=>x.text.replace(/\s+/g,'').replace('/mo','/month').replace('/yr','/year'));const plans=pat==='pricing'?makePlans(prompt,feats,ds,pr):[];const req=[...e.fields.map(x=>({label:title(x.text),source:`${x.reason}@${x.start}-${x.end}`})),...e.prices.map(x=>({label:x.text,source:`${x.reason}@${x.start}-${x.end}`})),...ds.map(x=>({label:`${x.target} ${x.effect} ${x.magnitude}`,source:`${x.span.reason}@${x.span.start}-${x.span.end}`})),{label:`${cta} CTA`,source:'action'}];
const headline=pat==='pricing'?`${prod} pricing for serious builders.`:pat==='dashboard'?`${prod} command center.`:pat==='settings'?`${prod} control console.`:pat==='checkout'?`${prod} checkout summary.`:pat==='chat'?`${prod} support workspace.`:`${prod} custom interface.`;
const subhead=pat==='pricing'?`${plans.length} tiers with ${pr[0]?`plans from ${pr[0]}`:'clear packaging'}, studio-grade emphasis, and ${feats.slice(0,3).join(', ').toLowerCase()}.`:`${prod} converts the prompt into a composed interface with ${feats.slice(0,3).join(', ').toLowerCase()}.`;
return{pattern:pat,strategy:pat==='pricing'?'grid':'composed',product:prod,headline,subhead,action:cta,features:feats,plans,metrics:[{label:'Revenue',value:'$128k',delta:'+18%'},{label:'Users',value:'42k',delta:'+11%'},{label:'Health',value:'94%',delta:'stable'},{label:'Exports',value:'212',delta:'local'}],toggles:e.fields.length>2?e.fields.slice(0,6).map(x=>title(x.text)):['Private mode','Local exports','Telemetry off','Weekly digest'],messages:['New request received','AI suggested reply prepared','Internal note ready'],slots:['Tue 10:30','Wed 14:00','Thu 16:15','Fri 09:00'],lineItems:[{label:prod,value:'$79.00'},{label:'Taxes and fees',value:'$8.20'},{label:'Total',value:'$87.20'}],requirements:req.slice(0,12),directives:ds.map(x=>`${x.target}: ${x.effect} (${x.magnitude})`)}}
